### ISSUE TITLE
Graphics/X11/XScreenSaver.hsc is GPL

### ISSUE THREAD

**Issue by nomeata** [haskell-pkg-janitors/X11#30]
The file `Graphics/X11/XScreenSaver.hsc` is GPL, while the rest of the package is `BSD`. This would be a problem. Luckily, I hold the copyright to `XScreenSaver.hsc` (I originally wrote it for `arbtt`), so hereby I re-license it under the same terms as the `X11` bindings. @jotrk, do you agree?

**Comment by jotrk** [comment]
Sure, go ahead! I think I left it at GPL, because that's what it was initially, but I prefer BSD, too.

Btw. would you like to take over maintainership? There were no requests yet, but I think I won't be able to fulfill requests in the future.

**Comment by nomeata** [comment]
I haven’t looked at the code since I wrote it many years ago, so I don’t think I’m more qualified than anyone else who touches the `X11` code base. In fact, Daniel (current maintainer of `X11`) will likely know better how to fix issues if they arise. But if you want I’ll put my name in there.

**Comment by jotrk** [comment]
No worries, just leave the maintainership to me then. If an issue arises, I'll see if I can fix it, if not, I'll ping Daniel.
